ScribuntoException: Use value property not dynamic property
Bug: T330524
Change-Id: I69a102497fffb939c849d2836302068ac9eff3d0
(cherry picked from commit 033c69cfabcbed874ecefbb9207eb9ce3743eeec)